### ISSUE TITLE
Unicode characters interpretation

### ISSUE THREAD

**Issue by wikiti** [mbklein/dot-properties#5]
Good day!

First of all, thank you for your work and effort. This gem suits our needs perfectly by keeping comments, newlines, etc.

We're having some trouble by importing and exporting Unicode characters. For example, given this input as a file:

```properties
# arrows.properties
property=\u2192 This is a sentence \u2190
```

By openning the file with `DotProperties`, the unicode characters are interpreted:

```rb
require 'dot-properties'

props = DotProperties.load('arrows.properties')
puts props.to_s
# Outputs this:
# property=→ This is a sentence ←
```

The problem comes when the file is saved by using the Ruby's `File` interface:

```rb
File.open('arrows.out.properties', 'w') { |f| f.write props.to_s }
```

Which has unescaped unicode characters:

```properties
# arrows.out.properties
property=→ This is a sentence ←
```

Is there any way to revert the interpretation to unicode characters and keep them escaped?

Best regards,
Daniel

**Comment by mbklein** [comment]
Thanks for your feedback; I will look into this issue.
